version: '3'

services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - '8080:8080'
    environment: 
      # MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    container_name: sistemaalmacenes
    volumes: 
      - ./mysql:/var/lib/mysql/data